update bnbchain repo
electric-capital/crypto-ecosystems pull request #1114
Opened 2024-02-12 02:39 UTC by CocoStarZ

2024-02-25 05:45 UTC, jubos requested changes

2024-02-25 05:45 UTC, jubos commented on data/ecosystems/b/bnb-chain.toml
> +
These are either users or organizations and not repos.  You should either make sub ecosystems for them or hook up the existing sub ecosystems to BNBChain if they should be attributed to BNB.

2024-03-04 01:44 UTC, CocoStarZ commented
Reviews resolved.

2024-03-30 00:52 UTC, jubos requested changes

2024-03-30 00:52 UTC, jubos commented on data/ecosystems/b/bnb-chain.toml
> +  "https://github.com/Particle-Network",
Hi, please break these out into sub ecosystems files if they don't exist or use the existing names like "BakeryToken".  A lot of these github orgs roll up into other parent ecosystems, so it keeps the taxonomy more organized.

2024-06-20 00:37 UTC, closed without merging

2024-06-22 16:08 UTC, Hosseinom commented
Add new StarkNet and Cairo related projects