update icp ecosystem
electric-capital/crypto-ecosystems pull request #1442
Opened 2024-08-16 10:45 UTC by letmejustputthishere

2024-08-16 10:50 UTC, letmejustputthishere commented
@jubos pls merge at your convience

2024-09-06 22:47 UTC, jdesanto requested changes
Review requests are mostly to make repos public for indexing.

2024-09-06 22:47 UTC, jdesanto commented on data/ecosystems/i/ithreem.toml
> +url = "https://github.com/ithreem/i3m-website"
This should be removed or made public. We cannot access it as is.

2024-09-13 07:28 UTC, letmejustputthishere commented
> Review requests are mostly to make repos public for indexing.

i'm not sure i can follow this. can you elaborate pls?

2024-09-13 07:35 UTC, letmejustputthishere commented on data/ecosystems/d/dfinity.toml
> +[[repo]]
this is public now

2024-09-13 07:37 UTC, letmejustputthishere commented
@jdesanto i incorporated your requested changes :) lmk if you want anything else to change.

2024-09-20 20:30 UTC, jdesanto commented
> > Review requests are mostly to make repos public for indexing.
> 
> i'm not sure i can follow this. can you elaborate pls?

Sorry this wasn't clear. Many repos were private and we cannot view them.

2024-09-23 07:05 UTC, letmejustputthishere commented
ah, ok! but now it's good to merge, right? we made some changes to avoid private repos in the future

2024-10-13 16:35 UTC, letmejustputthishere commented
hey @jdesanto can we please merge this PR, and afterwards [this](https://github.com/electric-capital/crypto-ecosystems/pull/1526)

2024-10-16 19:11 UTC, letmejustputthishere commented
hey @yizhao-ec, can you merge this one first pls and then the one you just reviewed?

2024-10-17 05:37 UTC, mariashen approved these changes
Thank you for the PR!

2024-10-18 04:24 UTC, merged