New projects built on Oasis - Update oasis.toml
electric-capital/crypto-ecosystems pull request #210
Opened 2022-07-16 14:58 UTC by MihneaOasis

2022-07-17 15:48 UTC, jubos requested changes
Please standardize the URL formats.

2022-07-17 15:48 UTC, jubos commented on data/ecosystems/o/oasis.toml
> +url = "https://github.com/therealbryanho/super-chad-adventures/blob/main/README.md"
These urls need to be the url of the root gitrepo: https://github.com/therealbryanho/super-chad-adventures

2022-07-18 06:17 UTC, MihneaOasis reviewed
FIle updated

2022-08-01 21:42 UTC, jubos commented
This still needs some improvements before it can be merged.  There are a lot of Github users in the repository section and still a few direct links to files instead of the repos.

2022-08-01 21:42 UTC, jubos requested changes
This still needs some improvements before it can be merged. There are a lot of Github users in the repository section and still a few direct links to files instead of the repos.

2023-01-05 19:42 UTC, jubos commented
Going to close this out for now.  Please reopen when it is ready for review after updating for the feedback.

2023-01-05 19:42 UTC, closed without merging