Telos Network Active repos
electric-capital/crypto-ecosystems pull request #239
Opened 2022-09-27 18:55 UTC by nathanduft44

Added Telos Network active repos under telos.toml. 

Next step is to create .tomls for the ecosystem.

2022-09-27 21:38 UTC, nathanduft44 reviewed
Added in the active developer repos building on Telos chain. 

- All have their own tomls ✅
-  Proper name in Telos Sub_ecosytem used ✅

More to be added in near future. We are really interested in our developer activity.

2022-10-13 15:56 UTC, nathanduft44 commented
Has anyone taken a look at this yet?

2022-10-13 18:42 UTC, donnyquixotic requested changes

2022-10-13 18:42 UTC, donnyquixotic commented on data/ecosystems/t/telos.toml
> +url = "https://github.com/telosnetwork/validators-nodehttps://github.com/telosnetwork/validators-node"
remove duplicate?

2022-10-13 18:42 UTC, donnyquixotic commented on data/ecosystems/t/telos.toml
>  url = "https://github.com/telosnetwork/ual-telos-keycat"
remove this entry, no longer maintained/supported

2022-10-13 19:25 UTC, donnyquixotic approved these changes

2022-10-17 15:56 UTC, 0xnirmal commented
@jubos @mariashen, any update on this?

2022-10-19 04:32 UTC, jubos requested changes
Thanks for these ecosystems.  Looks like a great start. 

Only changes required are to remove them from the sub ecos of Telos.

2022-10-19 04:32 UTC, jubos commented on data/ecosystems/t/telos.toml
> +    "DIA",
Most of these aren't dedicated Telos sub ecosystem.  We have a notion of primary and secondary ecosystems for the report, but this taxonomy only reflects primary ecosystems. 

Which of these are direct Telos subecos?

2022-10-19 04:32 UTC, jubos commented on data/ecosystems/s/symbiosis-finance.toml
> +url = "https://github.com/symbiosis-finance/DefiLlama-Adapters",
Please fix the trailing commas

2022-10-21 20:38 UTC, nathanduft44 commented
I went ahead and removed the Items from the sub-ecosystem list, temporarily until I fully understand what can be classified as a sub-eco under the Telos network. 

After taking a look at Avalanche and Solana it seems to be sub ecos must only be active on one-chain. A cross-chain DApp like Sushi Swap or ApeSwap doesn't qualify. - Is this correct please clarify. 🤔

Thanks!

2022-10-21 21:28 UTC, jubos commented
Yes, that's correct.  

For multichain ecos, if there is a repo that is specific to one ecosystem, that can be added manually to the toml file for that ecosystem.  For the report there is what we call a "primary" vs. "secondary" sub ecosystem relationship, but that it not yet exposed in this taxonomy.  

An example would be something like Sushi where the core governance and staking primitives are on Ethereum mainnet, but it has expanded to many other ecosystems.  So that one's primary parent is Ethereum and they have secondary relationships with many other chains.

2022-10-26 01:44 UTC, nathanduft44 commented
@jubos thanks for clarifying! I have temporarily removed the sub ecos from Telos. Will add in some primary ecosystems in the coming days. Would appreciate if you could merge the latest core Telos-Network repos under Telos.toml.

2022-10-29 19:03 UTC, merged

2022-10-29 19:03 UTC, jubos commented
Thanks, merged this.  Please open another PR when you have reviewed the sub ecosystems.