add ChaosDAO, GMorDIE, Stellaswap, TideLabs
electric-capital/crypto-ecosystems pull request #242
Opened 2022-10-04 04:15 UTC by spazcoin

* add ChaosDAO repos
* add GMorDIE parachain
* add Stellaswap to Moonbeam
* add Tide Labs. (Not on DOT/KSM relay, but substrate/rust based)

2022-10-04 04:17 UTC, spazcoin commented
FYI @x676f64 @arrudagates @tomen

2022-10-04 05:36 UTC, helloitsbirdo commented
A+

2022-10-13 15:27 UTC, jubos requested changes

2022-10-13 15:27 UTC, jubos commented on data/ecosystems/p/polkadot.toml
> +  "Stellaswap",
Moonbeam is a subecosystem of Polkadot already so don't need this here.

2022-10-13 15:27 UTC, jubos commented on data/ecosystems/p/polkadot.toml
> +  "Tide Labs",
Tide Labs shouldn't be part of Polkadot if they are just using substrate.  It is similar to chains using Tendermint.

2022-10-18 12:51 UTC, spazcoin commented
ok @jubos make your suggested corrected changes

2022-10-29 18:42 UTC, jubos commented
Merged this, thank you!

2022-10-29 18:42 UTC, closed without merging