Update aptos.toml
electric-capital/crypto-ecosystems pull request #335
Opened 2022-12-17 19:37 UTC by 0xneil

adding additional aptos ecosystem projects (https://github.com/aptos-foundation/ecosystem-projects)

2022-12-17 20:33 UTC, jckail approved these changes
Well done!

2022-12-22 05:39 UTC, jubos requested changes
This is a good start!

It will need some addition of the toml files for the individual sub ecosystems to land. 
Please look at #303 and #282 as examples of what the Moonbeam team did.  It makes the large diffs much easier to review.

Separately, the sub ecosystems are only "primary" sub ecosystems.  Most of these look like Aptos or Move subecosystems but projects like Celer are cross chain and are "supporting" only.  We don't have the supporting sub ecosystems attribute exposed in this taxonomy yet, but we will have it in the next year.

A few good rules of thumb for identifying sub ecosystems of Aptos:
1/ if the governance actions and/or governance token originates on the parent protocol, it is likely a sub ecosystem.
2/ if you go to the project's web page and it only mentions the parent ecosystem, it is likely a sub ecosystem.
3/ If the parent has a domain specific language, and the potential sub is implemented in it, then it is likely a sub ecosystem.  

Please let us know if you have any questions.

2022-12-22 19:47 UTC, jckail commented
Hey @jubos ! :) 

Really appreciate your help here, "Move" would not be considered an ecosystem by our interpretation, its a programming language not an ecosystem,  all of the sub ecosystems @0xneil included *SHOULD* meet the criteria of 1,2,3  -- could you help us understand where you think these don't meet the 3 criteria? 

Could you potentially link us to or share with us your definitions for your taxonomy? 

REALLY REALLY appreciate your help here :)

2022-12-22 19:51 UTC, jckail commented
Please help us understand what exactly needs to be done to get the correct attributions to aptos :)

2022-12-22 20:05 UTC, jckail commented
@jckail

2022-12-24 16:44 UTC, 0xneil commented
thanks for the feedback @jubos - made a few edits.

2023-01-04 16:56 UTC, gregnazario reviewed
Just some toml format issues for you @0xneil

2023-01-04 16:56 UTC, gregnazario commented on data/ecosystems/k/koizumi.toml
> +github_organizations = [https://github.com/KoizumiAPT]
This needs to be quoted

2023-01-04 16:56 UTC, gregnazario commented on data/ecosystems/p/patronusfi.toml
> +github_organizations = [https://github.com/patronusfi]
This needs to be quoted

2023-01-04 16:56 UTC, gregnazario commented on data/ecosystems/s/snotratech.toml
> +github_organizations = [https://github.com/snotratech]
This needs to be quoted

2023-01-04 16:56 UTC, gregnazario commented on data/ecosystems/u/umi-ag.toml
> +github_organizations = [https://github.com/umi-ag]
This needs to be quoted

2023-01-10 13:12 UTC, closed without merging