Solana projects
electric-capital/crypto-ecosystems pull request #41
Opened 2020-12-09 00:13 UTC by rmshea

Hey Electric Capital team,

I added a few repositories of note here. Thanks for keeping this updated!

Ryan

2020-12-09 00:35 UTC, jubos requested changes
Thanks for the PR, mind rebasing to master as I see a few duplicates in here.

2020-12-10 00:25 UTC, rmshea commented
hey @jubos sorry for the delay, just rebased.

2020-12-10 01:06 UTC, jubos requested changes
I think I might have tried to pull from the same list as you (Solana hackathon airtable) at some point but a lot of these repos 404 at this point.

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/Nebula-Wallet"
This is a github org instead of a repo.

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/solongwallet/solongext"
404 repo.

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/Xuriwork/spl-token-wallet"
404 repo.

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/ErJavid/solhackathondapp"
dup

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/decefi/decefi-solana"
404 repo

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/haggle-quest/solana-game"
404 repo

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/genesis-lab-team/solana-overview"
404

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/paul-schaaf/diy_etf"
dup

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/mehmeta/spl-token-wallet"
404

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/TitansFinance/apis-core/"
404

2020-12-10 01:06 UTC, jubos commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/anshuman73/contright"
404

2020-12-10 17:04 UTC, merged