Added Projects
electric-capital/crypto-ecosystems pull request #477
Opened 2023-03-21 15:28 UTC by GiupiDeLuca

I added the following projects: 
Mimo, UniFi, ZoomSwap, MinMax Finance, Parrot Defi, Magic Land, WOWswap, Cyclone, StarCrazy

2023-03-21 15:51 UTC, eherrerosj requested changes
Thanks for the PR @GiupiDeLuca! Left a few comments. Mainly 3 changes are needed:
1. adding all these projects under IoTeX toml so that it is seen as a parent 
2. removing duplicates
3. fixing one of the project titles

2023-03-21 15:51 UTC, eherrerosj commented on data/ecosystems/c/cyclone.toml
> +title = "Cyclone"
should also be added as a `sub_ecosystem` under IoTeX

2023-03-21 15:51 UTC, eherrerosj commented on data/ecosystems/m/magiclandfinance.toml
> +title = "Magic Land"
should also be added as a `sub_ecosystem` under IoTeX

2023-03-21 15:51 UTC, eherrerosj commented on data/ecosystems/p/parrotdefi.toml
> +title = "Parrot DeFi"
should also be added as a `sub_ecosystem` under IoTeX

2023-03-21 15:51 UTC, eherrerosj commented on data/ecosystems/w/wowswap.toml
> +title = "WOWswap"
should also be added as a `sub_ecosystem` under IoTeX

2023-03-21 15:51 UTC, eherrerosj commented on data/ecosystems/z/zoomswap.toml
> +title = "ZoomSwap"
should also be added as a `sub_ecosystem` under IoTeX

2023-03-22 20:23 UTC, GiupiDeLuca commented
Thanks for the feedback @eherrerosj - I think I should have everything now. 
- I deleted the duplicates
- Added the projects under iotex
- Fixed the wrong title

2023-03-22 21:27 UTC, GiupiDeLuca commented
@eherrerosj I have 2 checks failing, would you be able to help with those? Not sure what I did wrong. 😆

2023-03-23 15:03 UTC, eherrerosj commented
> @eherrerosj I have 2 checks failing, would you be able to help with those? Not sure what I did wrong. 😆

Thanks for the update. Not sure by 97fe is failing (can ignore), but f881It is failing because it's now a duplicate (seems like we have it already in our db), you can remove that addition then

2023-03-23 15:05 UTC, eherrerosj commented
yo can also bring the changes from your other PR to this one

2023-03-23 15:44 UTC, GiupiDeLuca commented
@eherrerosj I removed f881, I see there is minimax-finance, but it seems to be a different project than the MinMax Finance I added. Anyway, I also removed MinMax from the list of iotex sub_ecosystems for now, maybe later on we can check if these two are in fact different project with an almost identical name, or they are indeed the same. Thanks again for the feedback

2023-03-31 15:03 UTC, merged

2023-03-31 15:05 UTC, eherrerosj commented
thank you @GiupiDeLuca !