Updates to ergo ecosystem
electric-capital/crypto-ecosystems pull request #489
Opened 2023-04-26 06:20 UTC by glasgowm148

2023-04-29 14:39 UTC, glasgowm148 commented
Could this be merged please 🙏 @eherrerosj @jubos

2023-05-03 17:48 UTC, eherrerosj requested changes
Nice PR! Thanks for the contribution. I left some comments (most of them regarding renaming to non-human readable format). Let's workout those details and we should be good to merge

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/c/cardano.toml
> +  "spectrum-labs",
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-auction-house.toml
> +title = "ergo-auction-house"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-education.toml
> +title = "ergo-education"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-hackathons.toml
> +title = "ergo-hackathons"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-miner-tooling.toml
> +title = "ergo-miner-tooling"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-labs.toml
> -# Ecosystem Level Information
Why is this file removed?

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-names.toml
> +title = "ergo-names"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-raffle.toml
> +title = "ergo-raffle"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo-stats-analysis.toml
> +title = "ergo-stats-analysis"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/s/sigmausd.toml
> +#[[repo]] excluding as it generates a ton of commits
nice catch!

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/r/rosen-bridge.toml
> +title = "rosen-bridge"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/n/nightowl-casino.toml
> +title = "nightowl-casino"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/l/lithos-protocol.toml
> +title = "lithos-protocol"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/g/grand-gambit.toml
> +title = "grand-gambit"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-03 17:48 UTC, eherrerosj commented on data/ecosystems/e/ergo.toml
> -url = "https://github.com/mgpai22/ergosapiens"
why was this one removed?

2023-05-04 17:11 UTC, eherrerosj requested changes
forgot to comment on a few ecosystem names to keep the original human-readable ones

2023-05-04 17:11 UTC, eherrerosj commented on data/ecosystems/s/swamp-audio.toml
> +title = "swamp-audio"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-04 17:11 UTC, eherrerosj commented on data/ecosystems/z/zengate-global.toml
> +title = "zengate-global"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-04 17:11 UTC, eherrerosj commented on data/ecosystems/z/zk-treasury.toml
> +title = "zk-treasury"
Can you keep the original name please? We prefer human readable ecosystem names

2023-05-08 12:01 UTC, glasgowm148 commented
Updated

2023-05-08 17:12 UTC, eherrerosj requested changes
Almost there, left a couples comments and questions

2023-05-08 17:12 UTC, eherrerosj commented on data/ecosystems/z/zengate-global.toml
> +title = "Zengate Global"
please keep the original name as is

2023-05-08 17:12 UTC, eherrerosj commented on data/ecosystems/e/ergo.toml
> +    "ergo-developer-tooling",
please keep the original readable name

2023-05-08 17:12 UTC, eherrerosj commented on data/ecosystems/e/ergo-labs.toml
> -# Ecosystem Level Information
@glasgowm148

2023-05-09 18:51 UTC, merged

2023-05-09 19:41 UTC, glasgowm148 commented
Thanks for your help!