Add FENIX ecosystem
electric-capital/crypto-ecosystems pull request #503
Opened 2023-05-12 16:25 UTC by joeblau

Just watched @mariashen give a talk at BuildETH. Following up 🫡

2023-05-16 10:57 UTC, eherrerosj requested changes
hey @joeblau, thanks for the contribution. I see the Fenix is built on Ethereum. If so, please add "Fenix Protocol" to the list of sub_ecosystems on file ethereum.toml under data/ecosystems/e

2023-05-16 10:57 UTC, eherrerosj commented on data/ecosystems/f/fenix.toml
> +title = "Fenix Protocol"
hey @joeblau, thanks for the contribution. I see the Fenix is built on Ethereum. If so, please add "Fenix Protocol" to the list of sub_ecosystems on file `ethereum.toml` under `data/ecosystems/e`

2023-05-16 16:08 UTC, joeblau commented
FENIX will exist on 13 chains... Ethereum, BSC, Polygon, Avalanche, EthereumPOW, Moonbeam, Evmos, Fantom, DogeChain, OKChain, Arbitrum, Optimism, and PulseChain. Our community views the EVM as the value proposition, Ethereum is just one of the chains we're launching on.

That being said I've updated the PR.

2023-05-17 17:08 UTC, eherrerosj requested changes
We only need the ecosystem name in Ethereum, our scripts do the rest to come up with the entire tree of relations.

Wrt to the multi-chain compatibility. We have this internal concept of "primary" and "supported" ecosystems. We consider a relation between ecos to be primary when it has a currency / gov token in that network or it was originally built there and deployed afterwards to other chains. If Ethereum happen to not be the case of primary to Fenix please lmk

2023-05-17 17:08 UTC, eherrerosj commented on data/ecosystems/e/ethereum.toml
> +url = "https://github.com/atomizexyz/fenix"
you can remove this repo, since it's already in the Ethereum's child "Fenix" ecosystem

2023-05-23 10:44 UTC, eherrerosj approved these changes
Perfect, merging! Thank you for the contribution

2023-05-23 10:44 UTC, merged