Add Yield+ on EOS
electric-capital/crypto-ecosystems pull request #537
Opened 2023-06-29 23:45 UTC by DenisCarriere

2023-07-11 21:48 UTC, eherrerosj requested changes

2023-07-11 21:48 UTC, eherrerosj commented on data/ecosystems/y/yield-eos.toml
> +github_organizations = ["https://github.com/eosnetworkfoundation"]
EOS Network Foundation org is already part of Antelope, which is a child eco of EOS

2023-07-11 21:48 UTC, eherrerosj commented on data/ecosystems/y/yield-eos.toml
> +url = "https://github.com/defiboxswap/eosio.yield-ui"
Let's keep this one only

2023-11-06 18:53 UTC, eherrerosj commented on data/ecosystems/y/yield-eos.toml
> +url = "https://github.com/defiboxswap/eosio.yield-ui"
hey @DenisCarriere, were you able to take a look at my last comment?

2023-12-15 14:18 UTC, eherrerosj commented
Hi @DenisCarriere, we wanted to give you a heads-up that we are planning to freeze the data set that will be used for the analysis during the next few days. If you want your changes to be included and have an impact on this year’s report, please ensure that the requested modifications are made and merged prior to the data freeze.

Let's aim to have your PR finalized as soon as possible to make it into this window. If you have any questions or need further clarification, feel free to reply here or reach out directly.

2023-12-23 16:49 UTC, jubos commented
Manually merged this with 2b39ff7

2023-12-23 16:49 UTC, closed without merging