add 2 new repos and added renamed repos
electric-capital/crypto-ecosystems pull request #572
Opened 2023-08-23 18:34 UTC by CoinClubQuincy

I added 2 additional repos to the xdc.toml file and fixed 2 that were renamed

2023-09-06 00:24 UTC, eherrerosj approved these changes
Let some comment

2023-09-06 00:25 UTC, eherrerosj requested changes
can you remove the "/activity" URL suffix from the end of the 2 new repo URLs please?

2023-09-12 00:13 UTC, CoinClubQuincy commented
just fixed it thank you

2023-10-11 20:33 UTC, CoinClubQuincy commented
I added additional repos as well

2023-11-06 23:50 UTC, eherrerosj requested changes
left a comment, validator not passing due to this

2023-11-06 23:50 UTC, eherrerosj commented on data/ecosystems/x/xdc.toml
> +"
please move this double quote to the previous line

2023-11-20 16:29 UTC, eherrerosj approved these changes
thanks!

2023-12-15 14:19 UTC, eherrerosj commented
Hi @CoinClubQuincy, we wanted to give you a heads-up that we are planning to freeze the data set that will be used for the analysis during the next few days. If you want your changes to be included and have an impact on this year’s report, please ensure that the requested modifications are made and merged prior to the data freeze.

Let's aim to have your PR finalized as soon as possible to make it into this window. If you have any questions or need further clarification, feel free to reply here or reach out directly.

2023-12-19 19:12 UTC, merged