Freshen up subecosystems of Moonriver
electric-capital/crypto-ecosystems pull request #613
Opened 2023-10-10 06:11 UTC by themacexpert

This PR freshens a variety of ecosystems, adding missed repos and removing stale ones. This PR does not modify what is considered a subecosystem of Moonriver network.

2023-11-06 22:40 UTC, themacexpert commented
@eherrerosj Hey, is there anything I need to fix here?

2023-11-07 13:27 UTC, eherrerosj reviewed
nice PR, left a couple comments

2023-11-07 21:21 UTC, themacexpert commented on data/ecosystems/b/bware-labs.toml
> -url = "https://github.com/bwarelabs/aptos-core"
Not sure, I added it back

2023-11-07 21:21 UTC, themacexpert commented on data/ecosystems/o/onfinality.toml
>  github_organizations = []
Done

2023-11-08 15:57 UTC, eherrerosj commented
hey @themacexpert, you think we could add a missing tag instead of removing repos that don't exist anymore publicly? We prefer to keep non-existant repos so we know they existed at some point and we can keep their commits. 

Example: https://github.com/electric-capital/crypto-ecosystems/blob/master/data/ecosystems/h/helios-labs.toml#L11

2023-11-08 15:57 UTC, eherrerosj requested changes
left another comment

2023-11-08 19:48 UTC, themacexpert commented
@eherrerosj Done! The only remaining deletions are instances where repos have been renamed.

2023-11-14 18:47 UTC, themacexpert commented
Any other updates I need to make here? Thank you @eherrerosj

2023-11-20 16:33 UTC, eherrerosj commented
> Any other updates I need to make here? Thank you @eherrerosj

LGTM now, thank you for the work @themacexpert !

2023-11-20 16:33 UTC, merged