Freshen up subecosystems of Moonbeam
electric-capital/crypto-ecosystems pull request #616
Opened 2023-10-14 04:56 UTC by themacexpert

This PR freshens a variety of ecosystems, adding missed repos and removing stale ones. This PR does **not** modify what is considered a subecosystem of Moonbeam network.

2023-11-07 13:43 UTC, eherrerosj requested changes
left a few comments

2023-11-07 13:43 UTC, eherrerosj commented on data/ecosystems/m/moonbeans.toml
> +github_organizations = ["https://github.com/m00nbeans"]
unfortunately this is not an org link. Instead, it's a user link. Please remove it and add the repos that correspond individually.

2023-11-07 13:43 UTC, eherrerosj commented on data/ecosystems/m/moonwell.toml
> +url = "https://github.com/moonwell-fi/yield-server"
I'm seeing some changes that are going to conflict with your other PR (https://github.com/electric-capital/crypto-ecosystems/pull/613)

2023-11-07 13:43 UTC, eherrerosj commented on data/ecosystems/s/seascape-network.toml
> -url = "https://github.com/blocklords/sds-ts"
a lot of these were reassigned to https://github.com/seascapenetwork/... org, could you re-add them with the new owner instead please?

2023-11-07 13:43 UTC, eherrerosj commented on data/ecosystems/s/seascape-network.toml
>  github_organizations = ["https://github.com/blocklords"]
please add https://github.com/seascapenetwork/ here, it was renamed

2023-11-07 13:43 UTC, eherrerosj commented on data/ecosystems/t/toad-network.toml
> +github_organizations = ["https://github.com/ToadNetwork"]
nice

2023-11-08 15:58 UTC, eherrerosj requested changes
hey @themacexpert, you think we could add a missing tag instead of removing repos that don't exist anymore publicly? We prefer to keep non-existant repos so we know they existed at some point and we can keep their commits. 

Example: https://github.com/electric-capital/crypto-ecosystems/blob/master/data/ecosystems/h/helios-labs.toml#L11

2023-11-08 20:45 UTC, themacexpert commented
> hey @themacexpert, you think we could add a missing tag instead of removing repos that don't exist anymore publicly? We prefer to keep non-existant repos so we know they existed at some point and we can keep their commits.
> 
> Example: https://github.com/electric-capital/crypto-ecosystems/blob/master/data/ecosystems/h/helios-labs.toml#L11

Done!

2023-11-10 19:08 UTC, eherrerosj approved these changes
LGTM, nice work, thx!

2023-11-10 19:09 UTC, merged