Create smartloan.toml
electric-capital/crypto-ecosystems pull request #64
Opened 2021-04-17 13:53 UTC by Asvoria

Adding SmartLoan to celo electric capital

2021-04-19 21:23 UTC, jubos requested changes

2021-04-19 21:23 UTC, jubos commented on data/ecosystems/s/smartloan.toml
> +github_organizations = ["https://github.com/celo-org"]
Can you remove this github organization?

2021-04-19 21:23 UTC, jubos commented on data/ecosystems/s/smartloan.toml
> +sub_ecosystems = [ "celo" ]
Can you capitalize this?

2021-04-20 01:41 UTC, Asvoria reviewed
Done removed the organization and capitalized Celo

2021-05-18 16:59 UTC, jubos commented
This is failing the validation.  Can you rebase and fix?

2021-05-26 02:49 UTC, jubos commented
I merged your changes into the Celo ecosystem.  We can create a dedicated ecosystem when Smartloans are a bit further along.

2021-05-26 02:49 UTC, closed without merging