Include Movement ecosystem
electric-capital/crypto-ecosystems pull request #649
Opened 2023-11-09 22:53 UTC by 0xPrimata

Include Movement ecosystem
Include Movement as a sub ecosystem of Avalanche, Move, Aptos and Sui

2023-11-10 18:23 UTC, eherrerosj requested changes
left some comments

2023-11-10 18:23 UTC, eherrerosj commented on data/ecosystems/a/avalanche.toml
> +url = "https://github.com/ava-labs/go-ethereum"
can you keep the tags parameter below the URL like it was originally? not sure why it was changed

2023-11-10 18:23 UTC, eherrerosj commented on data/ecosystems/a/avalanche.toml
> +url = "https://github.com/ava-labs/coreth"
can you keep the tags parameter below the URL like it was originally? not sure why it was changed

2023-11-10 18:23 UTC, eherrerosj commented on data/ecosystems/a/avalanche.toml
> +url = "https://github.com/ava-labs/avalanche-wallet"
can you keep the tags parameter below the URL like it was originally? not sure why it was changed

2023-11-10 18:23 UTC, eherrerosj commented on data/ecosystems/a/aptos.toml
> +url = "https://github.com/aptos-labs/aptos-core"
can you keep the tags parameter below the URL like it was originally? not sure why it was changed

2023-11-10 18:23 UTC, eherrerosj commented on data/ecosystems/s/sui.toml
> +url = "https://github.com/MystenLabs/sui"
can you keep the tags parameter below the URL like it was originally? not sure why it was changed

2023-11-10 18:23 UTC, eherrerosj commented on data/ecosystems/s/sui.toml
> +url = "https://github.com/movemntdev/M1"
can remove

2023-11-23 12:45 UTC, ashucoder9 commented
Hey @eherrerosj, any updates on this PR? We want to make sure Movement Labs is included as a sub-ecosystem of Avalanche.

2023-11-23 14:05 UTC, eherrerosj approved these changes
LGTM, thanks for the contribution @0xPrimata ! Merging

2023-11-23 14:05 UTC, merged