Added missing org for IncrementFi
electric-capital/crypto-ecosystems pull request #663
Opened 2023-11-21 19:44 UTC by franklywatson

2023-11-23 13:35 UTC, eherrerosj requested changes
Added a comment

2023-11-23 13:35 UTC, eherrerosj commented on data/ecosystems/f/flow.toml
> +  "https://github.com/orgs/IncrementFi",
can you replace this org URL with adding IncrementFi as a subecosystem of Flow (see list at the beginning of this same file)?

2023-11-23 14:19 UTC, btspoony commented on data/ecosystems/f/flow.toml
I found that IncrementFi already exists in the sub-ecosystems, but just missing some repos:
https://github.com/electric-capital/crypto-ecosystems/blob/master/data/ecosystems/i/increment-finance.toml

2023-11-28 18:54 UTC, eherrerosj commented on data/ecosystems/f/flow.toml
@franklywatson could you please adjust the PR to add the missing repos to the existing toml?

2023-11-28 18:56 UTC, eherrerosj requested changes

2023-12-04 13:20 UTC, eherrerosj approved these changes

2023-12-04 13:20 UTC, merged