proj: add stader labs org + repos to the hedera config
electric-capital/crypto-ecosystems pull request #692
Opened 2023-12-11 14:11 UTC by prabhakar087

2023-12-11 16:30 UTC, eherrerosj requested changes
left a comment

2023-12-11 16:30 UTC, eherrerosj commented on data/ecosystems/h/hedera.toml
> +[repo]]
plz fix this typo

2023-12-12 17:28 UTC, prabhakar087 commented on data/ecosystems/h/hedera.toml
> +[repo]]
Fixed, thanks!

2023-12-14 20:37 UTC, eherrerosj approved these changes
thank you!

2023-12-14 20:38 UTC, merged