Adding Just Ape subecosystem & org
electric-capital/crypto-ecosystems pull request #741
Opened 2023-12-21 04:38 UTC by Just-Ape-Studios-Admin

Adding Just Ape name & org

2023-12-21 12:11 UTC, eherrerosj requested changes
Left a comment

2023-12-21 12:11 UTC, eherrerosj commented on data/ecosystems/s/solana.toml
> +  "Just Ape","
typo

2023-12-21 12:11 UTC, eherrerosj commented on data/ecosystems/s/solana.toml
> +  "Just Ape","
also, if you add an ecosystem here, there needs to exist a toml file with the same "title". I don't think we have a toml file for Just Ape. You have 2 options:
1. Delete this change and keep only the org change below
2. Create a toml file like just-ape.toml with the org in it and remove the org link from below

2023-12-23 17:40 UTC, closed without merging

2023-12-23 17:40 UTC, jubos commented
Going to close this out.  Please add the JustApe ecosystem repos and reopen when ready.