some icp additon repo
electric-capital/crypto-ecosystems pull request #778
Opened 2023-12-21 19:13 UTC by hrusikesh8280

2023-12-22 14:28 UTC, eherrerosj requested changes
left a comments

2023-12-22 14:28 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/DevKipesa/client"
how's this using ICP?

2023-12-22 14:28 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/GabrielPlus/Delicious"
how's this using ICP?

2023-12-22 17:19 UTC, hrusikesh8280 commented
i have reviewed the repos again and removed suggested changes, thanks for giving it a thorough look. Hope this helps

2023-12-22 17:58 UTC, eherrerosj requested changes
left a few more comments. Can you please make sure that the rest of the URLs are well formatted and that are repos that are actually using ICP please?

2023-12-22 17:58 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/Glinrear/Mavain/tree/main/identity_system/canisters/identity"
this repo URL format is incorrect

2023-12-22 17:58 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/Hexdee/OpenBridge"
how's this repo using ICP?

2023-12-22 17:58 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/SistemasTecTlaxiaco/cafeteriaMagnate1"
this one belongs to NEAR I believe

2023-12-23 06:43 UTC, hrusikesh8280 commented
> left a few more comments. Can you please make sure that the rest of the URLs are well formatted and that are repos that are actually using ICP please?
@eherrerosj , I have checked and corrected the format and removed unnecessary repos.

2023-12-23 18:17 UTC, jubos commented
Manually merged here [e6e0949](https://github.com/electric-capital/crypto-ecosystems/commit/e6e094980cd7161915b9fff5186915a5278060ca)

2023-12-23 18:17 UTC, closed without merging