Icp ecosystem changes
electric-capital/crypto-ecosystems pull request #779
Opened 2023-12-21 19:21 UTC by Mohdniyam

2023-12-22 14:39 UTC, eherrerosj requested changes
left a few comments

2023-12-22 14:39 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/Preeti-2507/TO-DO"
how's this repo using ICP?

2023-12-22 14:39 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/Sagarshah2004/Recipes"
can probably remove

2023-12-22 14:39 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> +url = "https://github.com/abhinav-nav/dakepper"
how's this ICP?

2023-12-22 17:49 UTC, Mohdniyam commented
Thank for reviewing @eherrerosj  , I have checked the repo list again and made the suggested changes as well as removed other unnecessary repos.

2023-12-22 18:15 UTC, eherrerosj requested changes
I checked a subset of the repos you are removing and I'm a bit confused on why they should be removed provided that they do build on top of ICP

2023-12-22 18:15 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> -url = "https://github.com/AkshatBhatnagar29/blockbashhack"
why is this repo being removed? It is actually ICP, no?

2023-12-22 18:15 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> -url = "https://github.com/Nishesh-singla/Blockchain"
why is this repo being removed? It is using actually ICP, no?

2023-12-22 18:15 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> -url = "https://github.com/diwakarsha/satworkshop"
why is this repo being removed? It is using actually ICP, no?

2023-12-22 18:15 UTC, eherrerosj commented on data/ecosystems/i/internet-computer.toml
> -url = "https://github.com/gurleenkaur164/gurleen"
why is this repo being removed? It is using actually ICP, no?

2023-12-23 05:52 UTC, Mohdniyam commented
@eherrerosj , I have reverted the unnecessary removal of repos, this happened due to not taking proper pull requests from master. Hope we are good to go now.

2023-12-23 18:21 UTC, jubos commented
Manually merged with [bdfaebb](https://github.com/electric-capital/crypto-ecosystems/commit/bdfaebb9618738aada649e95a89ae2c7036fc7b0)

2023-12-23 18:21 UTC, closed without merging