Adding chunky-metro repos
electric-capital/crypto-ecosystems pull request #794
Opened 2023-12-22 05:02 UTC by rhizanthemum

2023-12-22 16:03 UTC, eherrerosj requested changes
how are these contributing to Solana

2023-12-22 16:03 UTC, eherrerosj commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/chunky-metro/jupiter-ag-sdk"
missing

2023-12-22 16:03 UTC, eherrerosj commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/chunky-metro/december"
empty? can't see any code

2023-12-22 16:03 UTC, eherrerosj commented on data/ecosystems/s/solana.toml
> +url = "https://github.com/chunky-metro/chunkybot"
empty? can't see any code

2023-12-23 05:07 UTC, rhizanthemum commented
@eherrerosj these are all very early WIP but I removed the other two for now

2023-12-23 18:29 UTC, jubos commented
Manually merged here: [b2c8993](https://github.com/electric-capital/crypto-ecosystems/commit/b2c8993c97025e8c02f1aa95ed2a2f591cbcf83e)

2023-12-23 18:29 UTC, closed without merging