add YetAnotherCompany projects to starknet.toml
electric-capital/crypto-ecosystems pull request #834
Opened 2023-12-22 18:10 UTC by rcatalan98

2023-12-22 18:23 UTC, eherrerosj requested changes
You need to create a new ecosystem for Yet Another Company. For that, you need to create a new toml file like yet-another-company.toml with title "Yet Another Company" and add the org in it (https://github.com/yetanotherco)

2023-12-22 18:23 UTC, eherrerosj commented on data/ecosystems/s/starknet.toml
> -url = "https://github.com/JejomStark/ShellOnStark"
why remove?

2023-12-22 18:23 UTC, eherrerosj commented on data/ecosystems/s/starknet.toml
> -url = "https://github.com/Prop-House/prop-house-monorepo"
why remove?

2023-12-22 18:23 UTC, eherrerosj commented on data/ecosystems/s/starknet.toml
> +url = "https://github.com/yetanotherco/yet-another-bridge"
no need to add if you are creating a new ecosystem that includes this URL and adding such eco as a sub-eco of this eco

2023-12-22 18:23 UTC, eherrerosj commented on data/ecosystems/s/starknet.toml
> +  "Yet Another Company"
missing toml

2023-12-23 15:48 UTC, rcatalan98 commented
@eherrerosj your comments are already addressed thank you for taking the time to review it

2023-12-23 18:58 UTC, merged