Adding Rise In bootcamp community repos
electric-capital/crypto-ecosystems pull request #843
Opened 2023-12-22 18:52 UTC by Rise-In

2023-12-22 18:53 UTC, Rise-In commented
Adding BNB Chain projects

2023-12-22 21:28 UTC, Rise-In commented
Added Internet Computer repos and deleted 2 duplicate repos

2023-12-23 19:11 UTC, eherrerosj requested changes
lots of duplicates, can you please remove them? List is here:
https://github.com/electric-capital/crypto-ecosystems/actions/runs/7310009086/job/19918211744?pr=843#step:5:55

2023-12-23 19:11 UTC, eherrerosj commented on data/ecosystems/b/bnb-chain-bsc.toml
> +url = "https://github.com/srhtdmrkl/smart-tenders"
can you point out how's this built / deployed using BSC?

2023-12-23 19:11 UTC, eherrerosj commented on data/ecosystems/b/bnb-chain-bsc.toml
> +url = "https://github.com/berkaykarul/sushiswap"
sushiswap fork, remove

2023-12-23 19:11 UTC, eherrerosj commented on data/ecosystems/b/bnb-chain-bsc.toml
> +url = "https://github.com/AdityaCubicles45/Gitcode-v2"
can see Ethereum, Polygon and Avalanche, but not it using BSC (?)

2023-12-27 16:37 UTC, closed without merging