Create CrossWeave.Protocol.toml
electric-capital/crypto-ecosystems pull request #889
Opened 2023-12-23 07:49 UTC by NestorLtd

CrossWeave.Protocol.toml

2023-12-24 01:37 UTC, eherrerosj requested changes
the link added to orgs is a user link not an org link. Please keep the repo only and add the ecosytem name to the sub_ecosystems list of the compatible ecosystem(s) toml (s)

2023-12-24 04:06 UTC, NestorLtd commented
Ive done what you asked. Enjoy your Christmas time, see you all next year.

2023-12-24 13:13 UTC, eherrerosj commented
> Ive done what you asked. Enjoy your Christmas time, see you all next year.

I don't see it be part of any other ecosystem

2024-03-24 16:38 UTC, jubos requested changes

2024-03-24 16:38 UTC, jubos commented on data/ecosystems/c/CrossWeave.Protocol.toml
> +github_organizations = ["https://github.com/NestorLtd"]
This isn't an organization, it's a user.  Please remove it.

2024-05-25 19:43 UTC, jubos commented
Hi, please address the changes and reopen when it's ready. Thanks.

2024-05-25 19:43 UTC, closed without merging