Added MintEvents
electric-capital/crypto-ecosystems pull request #890
Opened 2023-12-23 08:04 UTC by Codeindeed

2023-12-24 01:38 UTC, eherrerosj requested changes
left a comment, only github orgs and repos are accepted URLs

2023-12-24 01:38 UTC, eherrerosj commented on data/ecosystems/m/mintevents.toml
> +github_organizations = ["https://github.com/Codeindeed"]
not an org

2024-03-24 16:35 UTC, jubos requested changes
Please see Enrique's comments above

2024-05-25 19:43 UTC, jubos commented
Going to close this one out.  Please address the feedback above and reopen when it's ready.

2024-05-25 19:43 UTC, closed without merging