Create mossdapp.toml
electric-capital/crypto-ecosystems pull request #968
Opened 2023-12-24 15:45 UTC by wenzhenxiang

2023-12-24 18:40 UTC, jubos requested changes
Looks good. Just needs some syntax fixes and can you add mossdapp to the appropriate ecosystem you are building in.  I assume Starknet.

2023-12-24 18:40 UTC, jubos commented on data/ecosystems/m/mossdapp.toml
> +github_organizations = [https://github.com/mossdapp]
Need quotes here.

2023-12-24 22:34 UTC, wenzhenxiang commented on data/ecosystems/m/mossdapp.toml
> +github_organizations = [https://github.com/mossdapp]
thanks

2023-12-26 10:05 UTC, eherrerosj approved these changes
LGTM now, thank you!

2023-12-26 10:05 UTC, merged